field: f2973c46-8e81-458f-ac59-1a537fc7e458 # Nursery Details
fieldLayouts:
  dc67a31a-ee3f-4686-85fe-c83d3a61e622:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0b0ac771-fd05-4192-91e5-e4835c35afaa # Nursery Name
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1974a3f-0a62-4731-be5b-403364b1fe79
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ed80db20-85e1-449d-8e46-e4c93c8321ee # Ofsted Number
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ca61f0f-3338-4183-8147-62b1bf246239
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a4af28ea-bbba-4d93-aa15-c4d50b557241 # Capacity
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8f86ece-3a32-4b69-a6eb-c71fba80cf4d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9b185155-bbe0-4bdd-8297-12108af8f0aa # Pin Number
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 59077141-f130-4348-a096-8754f35c8e9a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2ff31a9e-0104-4c7d-b9ba-5439e67c8c7e
        userCondition: null
fields:
  0b0ac771-fd05-4192-91e5-e4835c35afaa: # Nursery Name
    columnSuffix: bwbqfzuw
    contentColumnType: text
    fieldGroup: null
    handle: nurseryName
    instructions: null
    name: 'Nursery Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9b185155-bbe0-4bdd-8297-12108af8f0aa: # Pin Number
    columnSuffix: glrxvmlt
    contentColumnType: integer(10)
    fieldGroup: null
    handle: pinNumber
    instructions: null
    name: 'Pin Number'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: none
      size: 4
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  a4af28ea-bbba-4d93-aa15-c4d50b557241: # Capacity
    columnSuffix: hbaqlywc
    contentColumnType: integer(10)
    fieldGroup: null
    handle: capacity
    instructions: null
    name: Capacity
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  ed80db20-85e1-449d-8e46-e4c93c8321ee: # Ofsted Number
    columnSuffix: dpmbcrqz
    contentColumnType: text
    fieldGroup: null
    handle: ofstedNumber
    instructions: null
    name: 'Ofsted Number'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: details
name: Details
sortOrder: 1
