field: 674cbfed-c922-4e29-a598-fe0b9cfc61a4 # Basic Form Fields
fieldLayouts:
  42e6f597-651b-4ad3-bdef-a858782283a1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3c4ce1ec-bd52-4c96-b132-c03d303bc013 # Label
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 175a897d-8d01-4190-8c80-77bf94a08b96
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 744e843f-4e49-4349-8591-f604b23c0d8e # Handle
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e2d1afc-deb5-40df-89fd-3b00ba978b61
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1ad13c2c-9895-48c8-9bac-78540cd5c23e # Min Value
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8a643e3-2887-48c4-987e-69ae42d46fd2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 31614d76-ae3f-4d68-b67c-aec5c02cb46d # Max Value
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84b0f2fe-222e-4b8c-9d31-fca5487535f9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 01a73c71-a51a-4926-a1fb-a05e3327e942 # Required
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0eaccc6e-1905-4931-916c-5ca47e03ed59
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ebad38aa-8611-4716-8691-5d9413f006d4
        userCondition: null
fields:
  01a73c71-a51a-4926-a1fb-a05e3327e942: # Required
    columnSuffix: gtstyppj
    contentColumnType: boolean
    fieldGroup: null
    handle: required
    instructions: 'This field is required?'
    name: Required
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Lightswitch
  1ad13c2c-9895-48c8-9bac-78540cd5c23e: # Min Value
    columnSuffix: wqvsxzzp
    contentColumnType: integer(10)
    fieldGroup: null
    handle: minValue
    instructions: null
    name: 'Min Value'
    searchable: true
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: null
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Number
  3c4ce1ec-bd52-4c96-b132-c03d303bc013: # Label
    columnSuffix: rthrnrgn
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: null
    name: Label
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  744e843f-4e49-4349-8591-f604b23c0d8e: # Handle
    columnSuffix: ngyppvmi
    contentColumnType: text
    fieldGroup: null
    handle: fieldHandle
    instructions: null
    name: Handle
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  31614d76-ae3f-4d68-b67c-aec5c02cb46d: # Max Value
    columnSuffix: pcexqpax
    contentColumnType: integer(10)
    fieldGroup: null
    handle: maxValue
    instructions: null
    name: 'Max Value'
    searchable: true
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: null
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Number
handle: number
name: Number
sortOrder: 5
