field: 674cbfed-c922-4e29-a598-fe0b9cfc61a4 # Basic Form Fields
fieldLayouts:
  481fd89b-9161-471e-b459-716bbe5e15da:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4eea262a-cc00-4ba2-b352-d482426c1474 # Label
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a49533fa-9564-42f2-8634-edddbd8118f5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 342bbcfa-1366-4d3d-9f65-017e650bdd04 # Handle
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97abcb57-b042-4615-9d0a-9974c2b87311
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3d897cea-a76a-4a56-acc8-a529f3cd416f # Options
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c052e43-1a51-408b-88d7-9e29ec3fb4c1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 08aac443-159d-4624-959c-52132baa560b # Required
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d09b099-a28e-4fd6-81f1-6f86cf93ca24
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1a7a7859-b485-4d5f-8266-6f98ab3d1ced
        userCondition: null
fields:
  3d897cea-a76a-4a56-acc8-a529f3cd416f: # Options
    columnSuffix: jothtgad
    contentColumnType: text
    fieldGroup: null
    handle: options
    instructions: null
    name: Options
    searchable: true
    settings:
      addRowLabel: 'Add an option'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - 'Option Label'
                -
                  - handle
                  - optionLabel
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Value
                -
                  - handle
                  - value
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
      maxRows: null
      minRows: 1
      staticRows: false
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Table
  4eea262a-cc00-4ba2-b352-d482426c1474: # Label
    columnSuffix: esmewykb
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: null
    name: Label
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  08aac443-159d-4624-959c-52132baa560b: # Required
    columnSuffix: rjwnrscu
    contentColumnType: boolean
    fieldGroup: null
    handle: required
    instructions: 'This field is required?'
    name: Required
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Lightswitch
  342bbcfa-1366-4d3d-9f65-017e650bdd04: # Handle
    columnSuffix: rhalkxll
    contentColumnType: text
    fieldGroup: null
    handle: fieldHandle
    instructions: null
    name: Handle
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: radioButtons
name: 'Radio Buttons'
sortOrder: 4
