field: f408a044-177d-45e0-ab87-c674f6dff93e # Add Plan
fieldLayouts:
  c857ab9b-693e-48c4-9b09-0fc1cc8bb022:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: be8a3a70-687d-4779-9988-ac0db6851d5b # Select Plan
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36320783-9065-4785-90b8-a59a9926c48f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3860ee34-f854-4b24-9477-ef53e4eda957 # Custom Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2bcb74ee-e7ee-4329-ac39-24394e5b5518
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 08f0ae91-70d6-4a9f-9006-8964d685ac77 # Setup Fee
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b2e7270-f451-4e88-bb8b-7c6bc4d51195
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 75480194-ca7f-4d84-85d0-9235dd63e837 # Default
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82b78746-c28d-45a5-84f3-c6e8d64033ef
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 213e3dfa-1d76-4083-b8cf-ed9d3b17a9c5
        userCondition: null
fields:
  08f0ae91-70d6-4a9f-9006-8964d685ac77: # Setup Fee
    columnSuffix: incgxzmd
    contentColumnType: 'decimal(12,2)'
    fieldGroup: null
    handle: setupFee
    instructions: 'Setup Fee for the first payment'
    name: 'Setup Fee'
    searchable: true
    settings:
      decimals: 2
      defaultValue: null
      max: null
      min: null
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Number
  3860ee34-f854-4b24-9477-ef53e4eda957: # Custom Label
    columnSuffix: zwwlarkb
    contentColumnType: text
    fieldGroup: null
    handle: customLabel
    instructions: 'Override the default text displayed for each plan (i.e. “Nickname amount/interval”)'
    name: 'Custom Label'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: 'Awesome Plan $35.00/month'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  75480194-ca7f-4d84-85d0-9235dd63e837: # Default
    columnSuffix: moxedimn
    contentColumnType: boolean
    fieldGroup: null
    handle: default
    instructions: 'Please make sure that just one default is enabled'
    name: Default
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Lightswitch
  be8a3a70-687d-4779-9988-ac0db6851d5b: # Select Plan
    columnSuffix: ljyeyunr
    contentColumnType: string
    fieldGroup: null
    handle: selectPlan
    instructions: 'Can''t see your plans? Go to [Subscriptions](https://jackpot.arrivalhost.co.uk/admin/enupal-stripe/settings/subscriptions) and click on Refresh Plans'
    name: 'Select Plan'
    searchable: true
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - 'Select Plan...'
            -
              - value
              - ''
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Dropdown
handle: subscriptionPlan
name: 'Subscription Plan'
sortOrder: 1
