columnSuffix: null
contentColumnType: string
fieldGroup: b92bd8cf-5142-4835-8fb2-7ba810219633 # Nursery Details
handle: nurseryDetails
instructions: null
name: 'Nursery Details'
searchable: false
settings:
  contentTable: '{{%matrixcontent_nurserydetails}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
