columnSuffix: gjlorsjp
contentColumnType: text
fieldGroup: 6f68f391-331f-4987-828b-35085f975d33 # Results
handle: secondPrizeSubTitle
instructions: null
name: 'Second Prize Sub Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
