columnSuffix: null
contentColumnType: string
fieldGroup: 0d3a95d2-6843-4324-b92e-9c118238fa7f # Common
handle: testimonialCard
instructions: null
name: 'Testimonial Card'
searchable: false
settings:
  contentTable: '{{%matrixcontent_testimonialcard}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
