columnSuffix: scxjbyas
contentColumnType: text
fieldGroup: 0d3a95d2-6843-4324-b92e-9c118238fa7f # Common
handle: wysiwyg
instructions: null
name: Wysiwyg
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: true
  removeEmptyTags: false
  removeInlineStyles: false
  removeNbsp: false
  tinymceConfig: null
translationKeyFormat: null
translationMethod: none
type: spicyweb\tinymce\fields\TinyMCE
